In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset = pd.read_csv("/content/bank-full.csv",';')
dataset.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [3]:
dataset["y"].value_counts()

no     39922
yes     5289
Name: y, dtype: int64

In [4]:
dataset.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [5]:
dataset.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [6]:
dataset.y.replace(to_replace=['no','yes'], value = [0,1],inplace = True)

In [7]:
dataset["y"].value_counts()

0    39922
1     5289
Name: y, dtype: int64

In [8]:
dataset = dataset[['y','age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month','duration','campaign', 'pdays',
       'previous', 'poutcome']]

In [9]:
dataset.head()

y  age           job  marital  education default  balance housing loan  \
0  0   58    management  married   tertiary      no     2143     yes   no   
1  0   44    technician   single  secondary      no       29     yes   no   
2  0   33  entrepreneur  married  secondary      no        2     yes  yes   
3  0   47   blue-collar  married    unknown      no     1506     yes   no   
4  0   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome  
0  unknown    5   may       261         1     -1         0  unknown  
1  unknown    5   may       151         1     -1         0  unknown  
2  unknown    5   may        76         1     -1         0  unknown  
3  unknown    5   may        92         1     -1         0  unknown  
4  unknown    5   may       198         1     -1         0  unknown

In [10]:
data1 = pd.get_dummies(dataset,columns=['job', 'marital', 'education', 'default', 'housing','loan', 'contact','month', 'poutcome'])

In [11]:
data1.head()

y  age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0  0   58     2143    5       261         1     -1         0           0   
1  0   44       29    5       151         1     -1         0           0   
2  0   33        2    5        76         1     -1         0           0   
3  0   47     1506    5        92         1     -1         0           0   
4  0   33        1    5       198         1     -1         0           0   

   job_blue-collar  ...  month_jun  month_mar  month_may  month_nov  \
0                0  ...          0          0          1          0   
1                0  ...          0          0          1          0   
2                0  ...          0          0          1          0   
3                1  ...          0          0          1          0   
4                0  ...          0          0          1          0   

   month_oct  month_sep  poutcome_failure  poutcome_other  poutcome_success  \
0          0          0                 0               0                 0   
1          0          0                 0               0                 0   
2          0          0                 0               0                 0   
3          0          0                 0               0                 0   
4          0          0                 0               0                 0   

   poutcome_unknown  
0                 1  
1                 1  
2                 1  
3                 1  
4                 1  

[5 rows x 52 columns]

In [12]:
#model building

In [13]:
#independent & dependent variables
X = data1.iloc[:,1::]
y= data1.iloc[:,0]

In [14]:
X

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0       58     2143    5       261         1     -1         0           0   
1       44       29    5       151         1     -1         0           0   
2       33        2    5        76         1     -1         0           0   
3       47     1506    5        92         1     -1         0           0   
4       33        1    5       198         1     -1         0           0   
...    ...      ...  ...       ...       ...    ...       ...         ...   
45206   51      825   17       977         3     -1         0           0   
45207   71     1729   17       456         2     -1         0           0   
45208   72     5715   17      1127         5    184         3           0   
45209   57      668   17       508         4     -1         0           0   
45210   37     2971   17       361         2    188        11           0   

       job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  \
0                    0                 0  ...          0          0   
1                    0                 0  ...          0          0   
2                    0                 1  ...          0          0   
3                    1                 0  ...          0          0   
4                    0                 0  ...          0          0   
...                ...               ...  ...        ...        ...   
45206                0                 0  ...          0          0   
45207                0                 0  ...          0          0   
45208                0                 0  ...          0          0   
45209                1                 0  ...          0          0   
45210                0                 1  ...          0          0   

       month_may  month_nov  month_oct  month_sep  poutcome_failure  \
0              1          0          0          0                 0   
1              1          0          0          0                 0   
2              1          0          0          0                 0   
3              1          0          0          0                 0   
4              1          0          0          0                 0   
...          ...        ...        ...        ...               ...   
45206          0          1          0          0                 0   
45207          0          1          0          0                 0   
45208          0          1          0          0                 0   
45209          0          1          0          0                 0   
45210          0          1          0          0                 0   

       poutcome_other  poutcome_success  poutcome_unknown  
0                   0                 0                 1  
1                   0                 0                 1  
2                   0                 0                 1  
3                   0                 0                 1  
4                   0                 0                 1  
...               ...               ...               ...  
45206               0                 0                 1  
45207               0                 0                 1  
45208               0                 1                 0  
45209               0                 0                 1  
45210               1                 0                 0  

[45211 rows x 51 columns]

In [15]:
y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn import metrics

In [17]:
#Machine Learning Algorithm
#Fitting the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0)
model.fit(X,y)

LogisticRegression(random_state=0)

In [18]:
model.intercept_

array([-0.27878172])

In [19]:
np.round(model.coef_,2)

array([[-0.02,  0.  , -0.01,  0.  , -0.4 ,  0.  , -0.11, -0.03, -0.25,
        -0.03, -0.01,  0.01,  0.16, -0.02, -0.09,  0.03, -0.07,  0.  ,
         0.  ,  0.02, -0.17, -0.12, -0.07, -0.27,  0.05,  0.01, -0.26,
        -0.02,  0.36, -0.64, -0.08, -0.2 ,  0.09,  0.05, -0.42,  0.04,
         0.02,  0.03, -0.01, -0.01, -0.08, -0.06,  0.09, -0.4 , -0.06,
         0.1 ,  0.07, -0.13, -0.03,  0.31, -0.42]])

In [20]:
y_pred = model.predict(X)

In [21]:
y_pred_df = pd.DataFrame({'actual':y,
                          'predicted_values':model.predict(X)})

In [22]:
y_pred_df

actual  predicted_values
0           0                 0
1           0                 0
2           0                 0
3           0                 0
4           0                 0
...       ...               ...
45206       1                 1
45207       1                 0
45208       1                 1
45209       0                 0
45210       0                 0

[45211 rows x 2 columns]

In [23]:
y_pred_df["actual"].value_counts()

0    39922
1     5289
Name: actual, dtype: int64

In [24]:
y_pred_df["predicted_values"].value_counts()

0    43254
1     1957
Name: predicted_values, dtype: int64

In [25]:
#Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ac
confusion_matrix = confusion_matrix(y,y_pred)
print(confusion_matrix)

[[39140   782]
 [ 4114  1175]]


In [26]:
ac(y,y_pred)

0.8917077702329079

In [27]:
# conclusion model is 89% accurate

In [28]:
#Classification Report
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94     39922
           1       0.60      0.22      0.32      5289

    accuracy                           0.89     45211
   macro avg       0.75      0.60      0.63     45211
weighted avg       0.87      0.89      0.87     45211



In [29]:
# train test predictions

In [50]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=12)
model1 = LogisticRegression()
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)

In [51]:
y_pred_df1 = pd.DataFrame({'actual':y_test,
                          'predicted_values':model1.predict(X_test)})

In [34]:
y_pred_df1

actual  predicted_values
38440       0                 0
40402       1                 0
3708        1                 0
37421       0                 0
12526       0                 0
...       ...               ...
23464       0                 0
11742       0                 0
28291       0                 0
45162       1                 0
34838       0                 0

[13564 rows x 2 columns]

In [35]:
y_pred_df1["actual"].value_counts()

0    11990
1     1574
Name: actual, dtype: int64

In [37]:
y_pred_df1["predicted_values"].value_counts()

0    12963
1      601
Name: predicted_values, dtype: int64

In [39]:
#Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ac
confusion_matrix = confusion_matrix(y_test,y_pred1)
print(confusion_matrix)

[[11749   241]
 [ 1214   360]]


In [41]:
ac(y_test,y_pred1)

0.8927307578885284

In [43]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94     11990
           1       0.60      0.23      0.33      1574

    accuracy                           0.89     13564
   macro avg       0.75      0.60      0.64     13564
weighted avg       0.87      0.89      0.87     13564



In [44]:
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree

In [52]:
model2 = DecisionTreeClassifier(criterion = 'gini',min_samples_split=5,max_depth=10)
model2.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=10, min_samples_split=5)

In [54]:
y_pred2=model2.predict(X_test)
y_pred2

array([0, 1, 0, ..., 0, 1, 0])

In [56]:
y_pred_df2 = pd.DataFrame({'actual':y_test,
                          'predicted_values':model2.predict(X_test)})
y_pred_df2

actual  predicted_values
38440       0                 0
40402       1                 1
3708        1                 0
37421       0                 0
12526       0                 0
...       ...               ...
23464       0                 0
11742       0                 0
28291       0                 0
45162       1                 1
34838       0                 0

[13564 rows x 2 columns]

In [57]:
y_pred_df2["actual"].value_counts()

0    11990
1     1574
Name: actual, dtype: int64

In [58]:
y_pred_df2["predicted_values"].value_counts()

0    12494
1     1070
Name: predicted_values, dtype: int64

In [59]:
#Confusion Matrix for the model accuracy
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ac
confusion_matrix = confusion_matrix(y_test,y_pred2)
print(confusion_matrix)

[[11567   423]
 [  927   647]]


In [60]:
ac(y_test,y_pred2)

0.9004718372161604

In [48]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.93      0.96      0.94     11990
           1       0.60      0.41      0.49      1574

    accuracy                           0.90     13564
   macro avg       0.76      0.69      0.72     13564
weighted avg       0.89      0.90      0.89     13564

